# Generated by Django 5.1.3 on 2025-03-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
